"""empty message

Revision ID: 19932c6c76d9
Revises: 334ad2da1c31
Create Date: 2014-06-18 23:07:53.683068

"""

# revision identifiers, used by Alembic.
revision = '19932c6c76d9'
down_revision = '334ad2da1c31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
