"""empty message

Revision ID: 334ad2da1c31
Revises: 438422ea45fa
Create Date: 2014-06-18 23:06:29.259471

"""

# revision identifiers, used by Alembic.
revision = '334ad2da1c31'
down_revision = '438422ea45fa'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
