"""empty message

Revision ID: 3b17166067fe
Revises: None
Create Date: 2014-03-13 21:23:10.224731

"""

# revision identifiers, used by Alembic.
revision = '3b17166067fe'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
