"""empty message

Revision ID: 3caa78d26ad0
Revises: ecaa21db73
Create Date: 2014-06-23 22:32:56.801314

"""

# revision identifiers, used by Alembic.
revision = '3caa78d26ad0'
down_revision = 'ecaa21db73'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'downvotes')
    op.drop_column('threads', 'downvotes')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('threads', sa.Column('downvotes', sa.INTEGER(), nullable=False))
    op.add_column('comments', sa.Column('downvotes', sa.INTEGER(), nullable=False))
    ### end Alembic commands ###
