"""empty message

Revision ID: 438422ea45fa
Revises: 3df28505d4eb
Create Date: 2014-06-18 00:29:55.407834

"""

# revision identifiers, used by Alembic.
revision = '438422ea45fa'
down_revision = '3df28505d4eb'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
