"""empty message

Revision ID: 5757238ae1ad
Revises: 19932c6c76d9
Create Date: 2014-06-18 23:30:10.971370

"""

# revision identifiers, used by Alembic.
revision = '5757238ae1ad'
down_revision = '19932c6c76d9'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
