
"""empty message

Revision ID: ecaa21db73
Revises: 5757238ae1ad
Create Date: 2014-06-19 00:22:19.602300

"""

# revision identifiers, used by Alembic.
revision = 'ecaa21db73'
down_revision = '5757238ae1ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'rating',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'rating',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=False)
    ### end Alembic commands ###
